# -*- coding: utf-8 -*-
"""Stock_Price_Forecasting_Using_Recurrent_Neural_Networks_(RNN).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rCopX_xJtpjkMggNqej_dMbxCMrsm_qS
"""

!pip install yfinance -q

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

import yfinance as yf

from sklearn.preprocessing import MinMaxScaler
from sklearn.metrics import mean_squared_error

import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import SimpleRNN
from tensorflow.keras.layers import Dense
from tensorflow.keras.callbacks import EarlyStopping

df = yf.download(
    "AAPL",
    start = '2016-01-01',
    end = '2026-06-01'
)

df.head()

data = df[['Close']]
data.head()

plt.figure(figsize=(12,8))
plt.plot(data)
plt.title('Apple Stock Price')
plt.xlabel('Date')
plt.ylabel('Closing Price')
plt.show()

scaler = MinMaxScaler()
scaled = scaler.fit_transform(data)

def create_dataset(dataset, time_step=60):
  X = []
  y = []

  for i in range(len(dataset) - time_step):
    X.append(dataset[i:(i+time_step),0])
    y.append(dataset[i+time_step,0])

  return np.array(X), np.array(y)

X, y = create_dataset(
    scaled,
    60
)

print(X.shape)
print(y.shape)

train_size = int(len(X) * 0.8)

X_train = X[:train_size]
X_test = X[train_size:]

y_train = y[:train_size]
y_test = y[train_size:]

X_train = X_train.reshape(
    X_train.shape[0],
    X_train.shape[1],
    1
)

X_test = X_test.reshape(
    X_test.shape[0],
    X_test.shape[1],
    1
)

print(X_train.shape)
print(X_test.shape)

model = Sequential()

model.add(
    SimpleRNN(
        50,
        activation='tanh',
        input_shape=(60,1)
    )
)

model.add(Dense(1))

model.compile(
    optimizer='adam',
    loss = 'mse'
)

early_stop = EarlyStopping(
    monitor='val_loss',
    patience=5,
    restore_best_weights=True
)

history = model.fit(
    X_train,
    y_train,
    epochs=30,
    batch_size=32,
    validation_split=0.1,
    callbacks=[early_stop]
)

plt.figure(figsize=(10,5))

plt.plot(history.history['loss'])

plt.plot(history.history['val_loss'])

plt.legend([
    "Train",
    "Validation"
])

plt.show()

predictions = model.predict(X_test)

predictions = scaler.inverse_transform(
    predictions
)

actual = scaler.inverse_transform(
    y_test.reshape(-1,1)
)

rmse = np.sqrt(
    mean_squared_error(
        actual,
        predictions
    )
)

print("RMSE:",rmse)

plt.figure(figsize=(14,6))

plt.plot(
    actual,
    label="Actual"
)

plt.plot(
    predictions,
    label="Predicted"
)

plt.legend()

plt.show()

last_60_days = scaled[-60:]

future = []

current = last_60_days.reshape(1,60,1)

for i in range(30):
  pred = model.predict(
      current,
      verbose=0
  )

  future.append(
      pred[0][0]
  )

  current = np.append(
      current[:,1:,:],
      [[[pred[0][0]]]],
      axis=1
  )

future_prices = scaler.inverse_transform(
    np.array(future).reshape(-1,1)
)

plt.figure(figsize=(12,5))

plt.plot(
    future_prices
)

plt.title(
    "Next 30 Days Forecast"
)

plt.show()

